SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_SIZES = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_SPAWN_RATE_INCREASE = 0  # divisor for current time, default 60 no increase if 0
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_SIZES
ASTEROID_COLLISION = False

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOOT_COOLDOWN = 0.3

SHOT_SPEED = 500
SHOT_RADIUS = 5