from collision_types import CollisionBehaviour


# Shape
MIN_RADIUS = 10.0
SIZES = 5
MAX_RADIUS = MIN_RADIUS * SIZES

# Spawning
SPAWN_RATE = 0.8
SPAWN_RATE_INCREASE = 1
SPAWN_INVUL_TIME_IN_SEC = 5.0

# Splitting
SPLIT_SPEEDUP = 1.2
SPLIT_DIRECTIONS = (-1, 1)
SPLIT_ANGLE = (20, 50)

# Collision
COLLISION_ENABLED = False
ON_COLLISION = CollisionBehaviour.NOTHING

# Visual
BORDER_WIDTH_NORMAL = 2
BORDER_WIDTH_INVULNERABLE_MULTIPLIER = 4
INVULNERABILITY_BLINKING_PER_SECOND = 2
