from collision_types import CollisionBehaviour

ASTEROID_MIN_RADIUS = 20.0
ASTEROID_SIZES = 3
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_SIZES
ASTEROID_SPAWN_RATE = 0.8
ASTEROID_SPAWN_RATE_INCREASE = 1
ASTEROID_COLLISION_ENABLED = False
ASTEROID_SPLIT_SPEEDUP = 1.2
ASTEROID_SPLIT_DIRECTIONS = (-1, 1)
ASTEROID_SPLIT_ANGLE = (20, 50)
ASTEROID_ON_COLLISION = CollisionBehaviour.NOTHING
ASTEROID_COLLISION_OVERLAP = 2
ASTEROID_SPAWN_INVUL_TIME = 0
