from collision_types import CollisionBehaviour

MIN_RADIUS = 20.0
SIZES = 3
MAX_RADIUS = MIN_RADIUS * SIZES
SPAWN_RATE = 0.8
SPAWN_RATE_INCREASE = 1
SPLIT_SPEEDUP = 1.2
SPLIT_DIRECTIONS = (-1, 1)
SPLIT_ANGLE = (20, 50)
COLLISION_ENABLED = False
ON_COLLISION = CollisionBehaviour.NOTHING
SPAWN_INVUL_TIME = 0
